version: "2.1"

services:
  firefox:
    image: lscr.io/linuxserver/firefox:kasm-140.0.2build1-0ubuntu0.24.04.1mt1-ls3
    container_name: firefox
    network_mode: host
    security_opt:
      - seccomp=unconfined
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Shanghai
      - DOCKER_MODS=linuxserver/mods:universal-package-install
      - LC_ALL=zh_CN.UTF-8
      - INSTALL_PACKAGES=fonts-noto-cjk
      - CUSTOM_USER=admin
      - PASSWORD=admin
    volumes:
      - ./config:/config
    shm_size: "1gb"
    restart: unless-stopped